version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ../scripts/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbo-be-task
    ports:
      - "5432:5432"

  app:
    build:
      context: ..
      dockerfile: scripts/Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres